#!/usr/bin/env python

import rospy
from kinetic_sample_solvepnp_py.estimator_node import PoseEstimator

if __name__ == '__main__':
	# Initialize
	rospy.init_node('solvepnp_py', anonymous=True)

	pe = PoseEstimator()

	rospy.loginfo("Processing images...")

	# Loop here until quit
	try:
		rospy.spin()

	except rospy.ROSInterruptException:
		# Shutdown
		rospy.loginfo("Shutting down...")
		pe.shutdown()
		rospy.loginfo("Done!")

