#!/usr/bin/env python

import rospy
from kinetic_sample_sub_py.sub_node import Spinner

if __name__ == '__main__':
	# Initialize
	rospy.init_node('spinner_py', anonymous=True)

	sp = Spinner()

	rospy.loginfo("Spinning...")

	# Loop here until quit
	try:
		rospy.spin()

	except rospy.ROSInterruptException:
		# Shutdown
		rospy.loginfo("Shutting down...")
		sp.shutdown()
		rospy.loginfo("Done!")

