#!/usr/bin/env python

import rospy
from kinetic_sample_pub_py.pub_node import Pulser

if __name__ == '__main__':
	#Initialize
	rospy.init_node('pulser_py', anonymous=True)

	pl = Pulser()
	rate = rospy.Rate(10) # 10hz

	rospy.loginfo("Pulsing...")

	#Loop here until quit
	try:
		while not rospy.is_shutdown():
			pl.step()
			rate.sleep()

	except rospy.ROSInterruptException:
		#Shutdown
		rospy.loginfo("Shutting down...")
		pl.shutdown()
		rospy.loginfo("Done!")
