#!/usr/bin/env python

import rospy
from kinetic_sample_image_sub_py.sub_img_node import SubImg

if __name__ == '__main__':
	# Initialize
	rospy.init_node('img_sub_py', anonymous=True)

	si = SubImg()

	rospy.loginfo("Processing images...")

	# Loop here until quit
	try:
		rospy.spin()

	except rospy.ROSInterruptException:
		# Shutdown
		rospy.loginfo("Shutting down...")
		sp.shutdown()
		rospy.loginfo("Done!")

